//
//  NSUserDefaultKeys.h
//  SchoolBuy
//
//  Created by Hank on 15/6/16.
//  Copyright (c) 2015年 Hank. All rights reserved.
//

#ifndef SchoolBuy_NSUserDefaultKeys_h
#define SchoolBuy_NSUserDefaultKeys_h

//导航栏的颜色
#define kDefaultColor [UIColor colorWithRed:237/255.0 green:101/255.0 blue:90/255.0 alpha:1.0]
//灰色背景颜色
#define kDefaultBackColor [UIColor colorWithRed:245/255.0 green:245/255.0 blue:245/255.0 alpha:1.0]
//self的弱引用
#define WeakSelf(parameter) typeof(self) __weak weakSelf = parameter;

#define kModelKey @"modelKey"
#define kControllerKey @"controllerKey"
//API的Method
#define kConfirmOrderCarTotal @"mobileapi.cart.total"
#define kOrderPayInfo @"mobileapi.cart.payment_change"
#define kHomePageADList @"mobileapi.indexad.get_all_list"
#define kHotKeyWord @"mobileapi.keywords.get_all_list"
#define kGoodSList @"mobileapi.goods.get_all_list"
#define kGetCategory @"mobileapi.goods.get_cat"
#define kDetailProduct @"mobileapi.goods.get_item"
#define kAddCoupon @"mobileapi.cart.add_coupon"
#define kProductComment @"mobileapi.goods.comment"
#define kUserFavProduct @"mobileapi.member.favorite"
#define kUserDeleteFavPro @"mobileapi.member.del_fav"
#define kUserResetPassWord @"mobileapi.passport.resetpassword"
//#define kSendMobieCode @"mobileapi.passport.resetpassword"
#define kSendEmailCode @"mobileapi.passport.send_vcode_email"
#define kSimilarGood @"mobileapi.goods.goodslink"
#define kUserLogIn @"mobileapi.passport.post_login"
#define kUserLogOut @"mobileapi.passport.logout"
#define kGetSMSCode @"mobileapi.passport.send_vcode_sms"
#define kRegisteruser @"mobileapi.passport.member_create"
#define kSaveSetting @"mobileapi.member.save_setting"
#define kUpDataHeaderImage @"mobileapi.member.upload_image"
#define kUpDataPassWord @"mobileapi.member.save_security"
#define kAddFavItem @"mobileapi.member.add_fav"
#define kGetFavList @"mobileapi.member.favorite"
#define kDeleteFavGood @"mobileapi.member.del_fav"
#define kGetWallet @"mobileapi.member.get_member_wallet"
#define kGetAddressList @"mobileapi.member.receiver"
#define kDealAddress @"mobileapi.member.save_rec"
#define kDeleteAddr @"mobileapi.member.del_rec"
#define kAddComment @"mobileapi.member.send_msg"
#define kGetNeedCommetnOrder @"mobileapi.member.nodiscuss"
#define kGetOrder @"mobileapi.member.orders"
#define kGetArticleList @"mobileapi.article.help_item"
#define kGetArticleContent @"mobileapi.article.get_detail"
#define kCityNoLogIn @"mobileapi.passport.get_regions"
#define kLastFiveWater @"mobileapi.member.get_sorder"
#define kAddShopCar @"mobileapi.cart.add"
#define kGetRecommed @"mobileapi.goods.getcomment"
#define kGetPayMethod @"mobileapi.order.select_payment"
#define kFliterMethod @"mobileapi.goods.get_screen"
#define kGoodFliter @"mobileapi.goods.filter_get_goods"
#define kForgetPassWord @"mobileapi.passport.sendPSW"
#define kResetPassCheck @"mobileapi.passport.resetpwd_code"
#define kChangePayPass @"mobileapi.member.setpaypassword"
#define kMemberCoupon @"mobileapi.member.coupon"
#define kShopCarList @"mobileapi.cart.get_list"
#define kGoodBrandDetail @"mobileapi.goods.brand"
#define kLoadShopCarByGroup @"mobileapi.cart.get_list_group_by_tip"
#define kBatchDeleteGoodFromCar @"mobileapi.cart.batch_remove"
#define kBatchAddGoodFromCar @"mobileapi.cart.batch_add_cart"
#define kSignalDeleteGoodFromCar @"mobileapi.cart.remove"
#define kShopCarCheckOut @"mobileapi.cart.checkout"
#define kUpdateShopCarItemQuantity @"mobileapi.cart.update"
#define kOrderCreate @"mobileapi.order.create"
#define kOrderDoPayMent @"mobileapi.paycenter.dopayment"
#define kOrderWeiXinPay @"mobileapi.pay.weixinpay"  //微信sdk支付
#define kSuggestType @"mobileapi.info.get_suggest_type"
#define kAboutMeMehtod @"mobileapi.info.get_about"
#define kGetRegistedMember @"mobileapi.member.mobile_list"
#define kGetTextContent @"mobileapi.goods.get_invite_content"
#define kAddAttention @"mobileapi.member.attention"
#define kCancelAttention @"mobileapi.member.un_attention"
#define kWeChatCallBackMethod @"mobileapi.goods.weixin_pay"
#define kGetVersionMethod @"mobileapi.info.get_version"
#define kMyFenXiaoMethod @"mobileapi.member.get_members"
#define kSearchMemberByPhone @"mobileapi.member.find"
#define kSearchOrder @"mobileapi.member.find"
#define kProductMarketable @"microshop.special.change_marketable"
#define kMarketableAction @"microshop.special.edit_products"
#define kParaGetFinishOrder @"mobileapi.member.get_corder"
#define kParaGetUnFinishOrder @"mobileapi.member.get_ncorder"
#define kOrderChargeGetOrderList @"mobileapi.order.orderlist"
#define kCancelOrderMethod @"mobileapi.member.cancel"

#define OrderID @"orderID"
#define OrderPayMemtID @"OrderPayMemtID"
#define OrderPayCallBackURL @"OrderPayCallBackURL"
#define OrderPaySign @"OrderPaySign"

#define OrderWeChatPaySuccess @"OrderWeChatPaySuccess"
#define OrderWeChatPayFail @"OrderWeChatPayFail"
//参数字段
#define kParaMarketable @"marketable"
#define kParaGoodID @"goods_id"
#define kParaSearchValue @"value"
#define kParaComtype @"comtype"
#define kParaWeChatOrderID @"orderid"
#define kParaPaySign @"sign"
#define kParaMobiles @"mobiles"
#define kParaMemberID @"member_id"
#define kFansID @"fans_id"
#define kParaQuantity @"quantity"
#define kParaItems @"items"
#define kParaBrandID @"brand_id"
#define kParaJson @"json"
#define kParaSendId @"hipping[shipping_id]"
#define kParaSubject @"subject"
#define kParaContact @"contact"
#define kParaComment @"comment"
#define kParaData @"date"
#define kParaDirect @"direct"
#define kParaPageNo @"page_no"
#define kParaNPage @"n_page"
#define kParaMethod @"method"
#define kParaPageSize @"page_size"
#define kParaSign @"order_sign"
#define kParaObject @"son_object"
#define kParaBrandDetial @"brand_detail"
#define kParaItemId @"iid"
#define kParaCateId @"cat_id"
#define kParaSearchKeyWord @"search_keyword"
#define kParaOrderBy @"orderby"
#define kParaUserName @"uname"
#define kParaUserNameForPass @"username"
#define kParaPassWord @"password"
#define kParaVCode @"vcode"
#define kParaVCodeLong @"verifycode"
#define kParaPayPass @"pay_password"
#define kParaInfo @"info"
#define kParaType @"type"
#define kParaFile @"file"
#define kParaOldPass @"old_passwd"
#define kParaNewPass @"passwd"
#define kParaConfirmPass @"passwd_re"
#define kParaGid @"gid"
#define kParaAddressId @"addr_id"
#define kParaAddrArea @"area"
#define kParaAddrContent @"addr"
#define kParaAddrName @"name"
#define kParaAddrZipCode @"zip"
#define kParaAddrTel @"tel"
#define kParaAddrPhone @"mobile"
#define kParaAddrDef @"def_addr"
#define kParaAddrDis @"disabled"
#define kParaPayStatus @"pay_status"
#define kParaShipStatus @"ship_status"
#define kParaOrderStatus @"status"
#define kParaOrderTime @"createtime_status"
#define kParaOrderPage @"n_page"
#define KParaArticleId @"article_id"
#define kParaSaveName @"contact[name]"
#define kParaSaveImage @"contact[avatar]"
#define kParaRegionId @"p_region_id"
#define kParaProductID @"product_id"
#define kParaProductNum @"num"
#define kParaBuyCode @"buy_code"
#define kParaMechineID @"mid"
#define kParaBuyType @"btype"
#define kParaSendType @"send_type"
#define kParaAccount @"account"
#define kParaFirstPass @"login_password"
#define kParaSecPass @"psw_confirm"
#define kParaChangePay @"verifypaypassword"
#define kParaSetPay @"setpaypassword"
#define kParaObjType @"obj_type"
#define kParaObjIdent @"obj_ident"
#define kParaCoupon @"coupon"
#define kParaOldCouPon @"old_coupon"
#define kParaShipping @"shipping"
#define kParaAddress @"address"
#define kParaGoods @"goods"
#define kParaConfirmOrderPayMemt @"payment[pay_app_id]"
#define kParaMD5Info @"md5_cart_info"
#define kParaOrderID @"payment_order_id"
#define kParaOrderMethod @"payment_pay_app_id"
#define kParaOrderMoney @"payment_cur_money"
#define kParaCancelOrderID @"order_id"
#define kParaOldPayPassWord @"old_password"

#define kShopCarCurrentPrice @"ShopCarCurrentPrice"
#define kUpdateVersion @"UpdateVersion"
//Buy Type
#define kBuyFastType @"is_fastbuy"
#define kBuyFastTypeTwo @"isfastbuy"
#define kBuyCheckOutType @"no_checkout "
//Order type
#define kOrderByBuyCountDesc @"buy_count desc"
#define kOrderByBuyPriceDesc @"price asc"
//change price
#define kPriceChange @"PriceChange"
#define kPriceChangeNumber @"PriceChangeNumber"
#define kSelecteAllButton @"selectedAllButton"
#define kUnSelecteAllButton @"unselecteAllButton"
#define kSelecteTipID @"SelecteTipID"
//good status
#define kGoodSaleOff @"saleOff"
#define kGoodNoSaleOff @"noSaleOff"
//Order Status
#define kOrderWaitPayStatus @"waitToPay"
#define kOrderWaitPayTitle @"待付款"
#define kOrderWaitSendStatus @"waitToSend"
#define kOrderWaitSendTitle @"待发货"
#define kOrderWaitGetStatus @"waitToGet"
#define kOrderWaitGetTitle @"待收货"
#define kOrderWaitCommentStatus @"waitToComment"
#define kOrderWaitCommentTitle @"待评论"
#define kSearchResultDataPath [NSString stringWithFormat:@"%@/Documents/SearchResult.data",NSHomeDirectory()]


#define kNewVersionUrl @"NewVersionUrl"
#define kSearchHistoryKey       @"SearchHistoryKey"
#define kLogInNotificaKey @"AccountLogIn"
#define kLogOutNotificaKey @"AcountLogOut"
#define kChangeHeaderImage @"ChangeHeaderImage"
#define kChangeNickName @"ChangeNickName"
#define kChangeAccountInfo @"ChangeAccountInfo"

#define PREF_KEY_USERNAME @"logined_username"
#define PREF_KEY_UPASSWD @"logined_user_passwd"
#define NS_USERDEFAULT [NSUserDefaults standardUserDefaults]

#define kInLoadingText @"请稍后..."
#define kDeleteFavSuccess @"删除收藏成功"
#define kDeleteFavFail @"删除收藏失败"
#define kInLogInText @"正在登录"
#define kInSubmitText @"正在提交"
#define kInRegisterText @"正在注册"
#define kInSendCodeText @"正在发送"
#define kInCheckText @"正在验证"
#define kInUpdatingShopCar @"正在更新"
#define kPleaseLogIn @"请重新登录"
#define kChooseSkus @"请选择类型"
#define kLogInSuccessText @"登录成功"
#define kLogInFailText @"登录失败"
#define kRegisterSuccessText @"注册成功"
#define kRegisterFailText @"注册失败"
#define kLogOutSuccessText @"退出成功"
#define kLogOutFailText @"退出失败"
#define kAddFavItemSuccess @"收藏成功"
#define kDeleteFavItemSuccess @"删除收藏成功"
#define kChangeSuccess @"修改成功"
#define kChangeFail @"修改失败"
#define kLogInAgain @"重新登录"
#define kSendCodeAgain @"正在重新发送"
#define kHaveSendCode @"已发送验证码"
#define kPayPassSetSuccess @"支付密码设置成功"

#define kNoSetSchool @"请输入学校名称"
#define kNoSetCity @"请选择所在城市"
#define kNoSetSchoolDay @"请输入入学时间"
#define kNoSetName @"请输入名字"
#define kNoSetId @"请输入身份证号码"
#define kCorrectIdCardNum @"请输入正确的身份证号码"
#define kNotifiText @"请输入完整信息以完成注册"
#define kResponseKey @"rsp"
#define kFailKey @"fail"
#define kSuccKey @"succ"
#define kDataType @"data"
#define kLogInUserInfo @"LogInInfo"

#endif
